### ISSUE TITLE
Version 2.1.8 does not work

### ISSUE THREAD

**Issue by micah-uber** [pitbulk/wordpress-onelogin#10]
after i upgraded to the new version of the plugin and because it did not work I had to reinstall the old version, all works now.

Can we look into why the new version of the plugin does not work? I use wpengine as my hosting provider and have to use version 2.0.2

**Comment by pitbulk** [comment]
As you can read in the main page of the SAML plugin:
```
Using the SAML Plugin in WPengine or similar

This kind of WP hosting used to cache plugins and protect the wp-login.php view. You will need to contact them in order to disable the cache for this SAML plugin and also allow external HTTP POST to wp-login.php
```

Be sure that you did those steps. And if continue failing, let me know what problems you experienced so I can fix.
