### ISSUE TITLE
Error retrieving requestedAuthnContext

### ISSUE THREAD

**Issue by fralazar** [pitbulk/wordpress-onelogin#12]
Warning: in_array() expects parameter 2 to be array, string given' in /xxx/wp-content/plugins/onelogin-saml-sso/php/configuration.php:481

And the configuration form stops at:

requestedAuthnContext

showing no options in the multi-select.

**Comment by pitbulk** [comment]
Let me know if your problem is solved with this commit.

**Comment by fralazar** [comment]
Thanks that worked!
After that i had to change php/lib/Saml2/Response.php at line 57:
```
        $this->response = base64_decode($response);
        if($this->response === FALSE) {
            $this->response = $response;
        }
```
Since looks like the response from the SSO is not base64 encoded.
