### ISSUE TITLE
'Keep Local login' seems not to work

### ISSUE THREAD

**Issue by ApolloDS** [pitbulk/wordpress-onelogin#20]
Hi,
according to Release Notes in Version 2.3.0:
= 2.3.0 =
 * Add 'Keep Local login' functionality in order to prompt the normal login form + a SAML link instead of directly execute the SP-initiaited SSO flow

I enabled this setting but cannot see in Wordpress any SAML Link.
Where should this link be in /wp-admin.php?

**Comment by pitbulk** [comment]
Can you try 2.3.1?
https://github.com/pitbulk/wordpress-onelogin/releases/tag/v2.3.1

**Comment by ApolloDS** [comment]
Hello,
Great v2.3.1 does show the SAML Link :-)

So I hope it will be released soon in the "Plugin Store" of Wordpress.

Many thanks!
