### ISSUE TITLE
Upgrade the onelogin plugin to use SSO library version 2.4.0

### ISSUE THREAD

**Issue by johnliman** [pitbulk/wordpress-onelogin#5]
Hi @pitbulk , if I used the SSO library 2.3.0 contain in this plugin, I will get the following error when using the strict mode:
The response was received at https://mysite.com:80/wp-login.php instead of https://mysite.com/wp-login.php?saml_acs
There was at least one error processing the SAML Response: invalid_response
Contact the administrator

But if I use library version 2.4.0, the above error disappear.  Any chance you will update this plugin using the latest SSO library?

**Comment by pitbulk** [comment]
Sure, I will try to update it asap.

**Comment by pitbulk** [comment]
Done: https://github.com/pitbulk/wordpress-onelogin/commit/e6cbea058429b7dbfd8e0c8a9ffb072a7e957a2c
