### ISSUE TITLE
Developer hook for setting private/public keys

### ISSUE THREAD

**Issue by johnliman** [pitbulk/wordpress-onelogin#9]
Due to security reason, we normally store the sensitive information, such as private/public keys in environment variables, and not in the file nor database.

Are you able to extend the code to allow a developer to hook in to set the private/public keys?

**Comment by pitbulk** [comment]
Does Apache / Nginx read the public/private keys from environment variables?

If you provide a PR I will be able to review it and add this functionality to the WordPress plugin (and also on the SAML toolkit), but none of our customers required such feature.
